module.exports = require('scuttlebot')
  .use(require('scuttlebot/plugins/master'))
  .use(require('./persistent-gossip'))
  .use(require('./friends-with-scope-and-gossip-priority'))
  .use(require('scuttlebot/plugins/replicate'))
  .use(require('ssb-blobs'))
  .use(require('./invite-with-scope'))
  .use(require('scuttlebot/plugins/block'))
  .use(require('./local-with-list'))
  .use(require('scuttlebot/plugins/logging'))
  .use(require('scuttlebot/plugins/private'))
